apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: lucifer942/client
      context: client
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: lucifer942/comments
      context: comments
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: '*.js'
            dest: .
    - image: lucifer942/event-bus
      context: event-bus
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: '*.js'
            dest: .
    - image: lucifer942/moderation
      context: moderation
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: '*.js'
            dest: .
    - image: lucifer942/posts
      context: posts
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: '*.js'
            dest: .
    - image: lucifer942/query
      context: query
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: '*.js'
            dest: .